<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" />
    <link rel="stylesheet" href="css\register_user.css" />
</head>

<body>
    <div class="main-container">
        <div class="rectangle">
            <div class="rectangle-1"><span class="silape">SILAPE</span></div>
            <span class="register">REGISTER</span><span class="username-input">Username</span>
            <div class="rectangle-2"></div>
            <span class="password-input">Password</span>
            <div class="rectangle-3"></div>
            <span class="nama-input">Nama</span>
            <div class="main-content"></div>
            <span class="email-field">Email</span>
            <div class="rectangle-box"></div>
            <span class="address-field">Alamat</span>
            <div class="rectangle-box-4"></div>
            <span class="no-telp">No telp</span>
            <div class="rectangle-5"></div>
            <button class="rectangle-6">
                <span class="buat-akun">Buat akun</span></button><span class="kembali">Kembali</span>
        </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
</body>

</html>
