<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" />
    <link rel="stylesheet" href="css/edit-data-user.css" />
</head>

<body>
    <div class="main-container">
        <div class="rectangle">
            <button class="rectangle-button"></button><span class="edit-data">Edit data</span>
            <div class="logo-smart-peamekasan">

            </div>
            <span class="nama">Nama</span>
            <div class="rectangle-2">
                <div class="rectangle-3"></div>
            </div>
            <div class="rectangle-4"></div>
            <span class="tempat-lahir">Tempat lahir</span>
            <div class="rectangle-5"></div>
            <span class="tanggal-lahir">Tanggal lahir</span>
            <div class="rectangle-6"></div>
            <span class="no-tlp">No tlp</span>
            <div class="rectangle-8"></div>
            <span class="alamat">Alamat</span>
            <div class="rectangle-7"><span class="batal">Batal</span></div>
            <div class="rectangle-1"><span class="simpan">Simpan</span>
            </div>

        </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
</body>

</html>
